name: Validate / Yaml

on:
  workflow_call:
  workflow_dispatch:

jobs:
  yamllint:
    name: 🧹 Yaml Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out Repo
        uses: actions/checkout@v4

      - name: 🚀 Run yamllint
        run: yamllint --strict .
