name: 🧹 C++ Lint
inputs:
  token:
    description: Github Token
    required: true
runs:
  using: "composite"
  steps:
    - name: 🚀 Run C++ linter
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        style: file
        tidy-checks: '-*'
        files-changed-only: false
        step-summary: true
        format-review: ${{ github.event_name == 'pull_request' }}
        thread-comments: ${{ github.event_name == 'pull_request' }}

    - name: Fail fast?!
      if: steps.linter.outputs.checks-failed != 0
      run: |
        echo "Some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
        exit 1
      shell: bash
