name: Validate

on:
  workflow_call:
    inputs:
      exclude:
        description: "Exclude validation for..."
        required: false
        type: string
        default: "[]"

jobs:
  pre-commit:
    name: 🚸 Pre-commit
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      - name: 🔍 Check if pre-commit Сonfig exists
        id: check_config
        run: |
          if [ -f .pre-commit-config.yaml ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: 🐍 Set up Python
        if: steps.check_config.outputs.exists == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: 🛠️ Run pre-commit and Auto-fix
        if: steps.check_config.outputs.exists == 'true'
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
        continue-on-error: true
      - name: 🚸 Push fixes to PR
        if: always() && steps.check_config.outputs.exists == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Chore: Auto fixes by pre-commit hooks"
          branch: ${{ github.event.pull_request.head.ref }}
          create_branch: false
          skip_checkout: true
          skip_fetch: true
          push_options: '--force'

  changes:
    name: 👀 Source / Changed
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out Repo
        uses: actions/checkout@v6

      - name: ⚙️ Check for changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            python:
              - '**.py'
              - 'requirements.txt'
            yaml:
              - '**.yaml'
              - '**.yml'
            cpp:
              - '**.cpp'
              - '**.h'
            configs:
              - '**.xml'
              - '**.json'

  validate:
    name: 🧹 Validation
    if: ${{ needs.changes.outputs.changes != '[]' }}
    needs:
      - changes
    strategy:
      matrix:
        action: ${{ fromJSON(needs.changes.outputs.changes) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out Repo
        if: ${{ !contains(fromJSON(inputs.exclude), matrix.action) }}
        uses: "actions/checkout@v6"

      - name: 🧹 Validate
        if: ${{ !contains(fromJSON(inputs.exclude), matrix.action) }}
        uses: jenseng/dynamic-uses@v1
        with:
          uses: andrewjswan/actions/validation/${{ matrix.action }}@main
          with: '{ "token": "${{ secrets.GITHUB_TOKEN }}" }'

  ci-status:
    name: 🎭 Status
    runs-on: ubuntu-latest
    needs:
      - validate
    if: always()
    steps:
      - name: 🎉 Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: ❌ Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
